[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "reportz"
version = "0.1.0"
description = "A Python library"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Gaurav Kadam" }
]
dependencies = [
    "psutil>=5.9.0",
]

[project.scripts]
reportz = "reportz.cli:main"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

